move check before push
themuseblockchain/Muse-Source pull request #129
Opened 2018-08-01 23:52 UTC by oxarbitrage

cherry picked first but found there are a few differences with the bitshares core inside the check like `MUSE_BLOCK_INTERVAL` and `_delegate->get_blockchain_now()` so decided to make new commit with the spirit. Spirit is actually move the check before the push, this pull moves the MUSE check instead of cherry picking from bitshares.

tried a replay and found this issue when doing so: https://github.com/themuseblockchain/Muse-Source/issues/128

2018-08-01 23:54 UTC, oxarbitrage commented
forgot to mention this is for issue https://github.com/themuseblockchain/Muse-Source/issues/111

2018-08-02 12:55 UTC, pmconrad requested changes

2018-08-02 12:55 UTC, pmconrad commented on libraries/net/node.cpp
> +          originating_peer->number_of_unfetched_item_ids = blockchain_item_ids_inventory_message_received.total_remaining_item_count;
Please remove this line, it's a duplicate of line 2563 (otherwise this would be a breaking change).
Same in BitShares.

2018-08-03 14:51 UTC, pmconrad approved these changes
Thanks!

2018-08-03 14:51 UTC, merged